# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 515bfeb26fbfa5f2b2cbb613b4a3d7db5b480976460f97aae993709b02684a59756276f0b2db04c22adc7b96efb437b58bc42c4a062b15422f9a719223c6f6c2

test:
  secret_key_base: efd32fc27944ab322fc1ff14021d2b66cc779c97d7aa472b3e03d4b86969b5ae9575e7368a68eb059f05f82ff3755fc04eff9f921c995147323e1ee4b8d82f76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
